### ISSUE TITLE
Does this app allow me to disable the taskbar in one monitor out of 4 monitors?

### ISSUE THREAD

**Issue by TheMikeyRoss** [LuisThiamNye/ButteryTaskbar2#11]
Hi,

I have 4 monitors and I want to hide the taskbar on one of them. Windows 10 unfortunately doesn't have that built-in

Does this app allow me to achieve that?

**Comment by LuisThiamNye** [comment]
No.

**Comment by TheMikeyRoss** [comment]
![giphy](https://github.com/LuisThiamNye/ButteryTaskbar2/assets/97709651/6dafa961-3585-47f7-ad41-f9520f39faf6)
