### ISSUE TITLE
ButteryTaskbar2 cannot be removed

### ISSUE THREAD

**Issue by robertocsjr** [LuisThiamNye/ButteryTaskbar2#2]
Ok, I may be missing something here, but I have tried everything and cannot solve this issue.

I have downloaded and used butterytaskbar2 without configuring the initializing processes.

Now everytime I turn on my PC, the toolbar doesn't show up on mouse over. 
Is there some sort of service, registry, configuration that I need to delete to rollback the installation?

Thanks.

**Comment by LuisThiamNye** [comment]
The program should not be modifying anything like the registry or startup tasks; it is a simple executable that does not have an installer, so there is no installation/uninstallation except that which you have done yourself.

I do not have a lot of information to go on, so all I can think of is Windows doing something Weird like starting programs that were previously open, including Buttery Taskbar.

When you say the taskbar doesn’t show after you have restarted, is Buttery Taskbar actually running? That is, does it show when you press the Windows key? Can you disable it with Ctrl+Win+F11?

Also, have you used the old Buttery Taskbar? Do you have that installed?

**Comment by robertocsjr** [comment]
Ok, I figured it out... The problem was caused by a different program called RoundedTB...

Sorry for the trouble and thanks for the help
