### ISSUE TITLE
Add Option for Starting Toggled Off? 

### ISSUE THREAD

**Issue by Corasinth** [LuisThiamNye/ButteryTaskbar2#4]
This is kind of and edge case, but I was wondering if you could add an option to start the program with it's functionality disabled (as if you'd pressed the control win F11 shortucut), leaving it to be enabled later. 

You could do this with a config file, option in the settings menu, or just an alt executable that starts toggled off rather than on, whichever is easiest. 

I tried to see if I could just fork it but I'm not sure how to compile my own version of the executable (the main issue really), or if the `is_enabled` variable at the top of `buttery-taskbar.jai` is the value I would want to flip. 

ButteryTaskbar works great for me, but I don't always want my taskbar hidden and usually not when I'm just booting up. Having to input the shortcut every time is kind of a hassle, so this would make it easier to just have run on startup and toggle it on when I want the taskbar gone.

**Comment by LuisThiamNye** [comment]
The new release now remembers whether it was enabled or disabled when it starts up. See if that meets your needs, else write back.

It also has a settings window to provide a checkbox for enabling/disabling the program.

https://github.com/LuisThiamNye/ButteryTaskbar2/releases
