### ISSUE TITLE
Beep sound when scrolling at the bottom of screen on Windows 11

### ISSUE THREAD

**Issue by Texhnolyzing** [LuisThiamNye/ButteryTaskbar2#8]
Noticed a odd "BEEP" sound that happens almost every other time I try to open the taskbar using the mouse wheel scroll.
Has anyone else reproduced this before?

Windows 11, not any other taskbar mods installed but this one.

**Comment by XNINEZERO** [comment]
I can confirm I have this on occasion as well.  Not all the time, I'd say a few times a week.

**Comment by Texhnolyzing** [comment]
I can reproduce it fairly regularly if I scroll my wheel fast while moving down to the screen. And after the taskbar pops up while my mouse is on the taskbar May take a few attempts but felt like it was a fairly regular occurrence.Wonder if my machine is a bit more susceptible. On Nov 8, 2023, at 5:49 AM, Luis Thiam-Nye ***@***.***> wrote:﻿
I think I have experienced this once. I'm not sure why, and without reliable reproduction it could be unclear how to fix this one.

**Comment by LuisThiamNye** [comment]
Thank you for the information. With my mouse I can achieve a very high scroll rate which does indeed trigger the issue very reliably. So, I suppose I'll take a look at fixing this sometime when I have the time.

**Comment by LuisThiamNye** [comment]
Try the latest release (2.2.1) to see if that helps: https://github.com/LuisThiamNye/ButteryTaskbar2/releases
