### ISSUE TITLE
Feature Request: CTRL+WIN+F11 To Toggle "Automatically Hide Taskbar" As Well as Buttery Taskbar

### ISSUE THREAD

**Issue by XNINEZERO** [LuisThiamNye/ButteryTaskbar2#9]
Essentially, to have the standard fixed taskbar as the toggle for the CTRL+WIN+F11 hotkey, rather than the "Automatically Hide" mode.  

Buttery Taskbar ON - Windows Automatically Hide mode ON, Buttery Taskbar ON

Buttery Taskbar OFF - Fixed Taskbar.

Seems possible at face value.

Thanks in advance if you could give it a look.

**Comment by LuisThiamNye** [comment]
I'd need code that modifies Windows' auto-hide setting.

**Comment by LuisThiamNye** [comment]
I think you can do what you want as of the new version 2.3.0.
https://github.com/LuisThiamNye/ButteryTaskbar2/releases
